# ========================
# 公共配置（所有环境共享）
# ========================

spring:
  application:
    name: community

  # 多环境配置
  profiles:
    default: dev  # 默认开发环境

  # JPA 通用配置
  jpa:
    open-in-view: false  # 建议关闭，避免LazyInitializationException
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# 日志格式（所有环境统一）
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"

jwt:
  token-header: authorization
  short-ttl: 7200000
  long-ttl: 2592000000